### Data Loading

In this section, we import the required Python library and load all datasets into Pandas DataFrames for further analysis.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
orders = pd.read_csv("../data/raw/orders.csv")
order_items = pd.read_csv("../data/raw/order_items.csv")
order_item_refunds = pd.read_csv("../data/raw/order_item_refunds.csv")
website_sessions = pd.read_csv("../data/raw/website_sessions.csv")
website_pageviews = pd.read_csv("../data/raw/website_pageviews.csv")
products = pd.read_csv("../data/raw/products.csv")

### Organizing DataFrames

To avoid repeating code for each dataset, all DataFrames are stored in a dictionary. This allows us to iterate through every table efficiently during data exploration.

In [3]:
tables = {
    "Products": products,
    "Orders": orders,
    "Order Items": order_items,
    "Refunds": order_item_refunds,
    "Website Sessions": website_sessions,
    "Website Pageviews": website_pageviews
}

### Dataset Overview

##### Objective

Understand the structure of every dataset by examining:

- Number of rows and columns
- Column names
- Data types
- Missing values

This helps identify data quality issues before analysis.

In [4]:
for name, df in tables.items():
    print("=" * 50)
    print(name)
    # shape
    print("Shape:", df.shape)
    # columns
    print("Columns:", list(df.columns))
    # dtypes
    print("Data Types:")
    print(df.dtypes)
    # Missing values
    print("Missing Values:")
    print(df.isnull().sum())
    print()

==================================================
Products
Shape: (4, 3)
Columns: ['product_id', 'created_at', 'product_name']
Data Types:
product_id       int64
created_at      object
product_name    object
dtype: object
Missing Values:
product_id      0
created_at      0
product_name    0
dtype: int64

==================================================
Orders
Shape: (32313, 8)
Columns: ['order_id', 'created_at', 'website_session_id', 'user_id', 'primary_product_id', 'items_purchased', 'price_usd', 'cogs_usd']
Data Types:
order_id                int64
created_at             object
website_session_id      int64
user_id                 int64
primary_product_id      int64
items_purchased         int64
price_usd             float64
cogs_usd              float64
dtype: object
Missing Values:
order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

==================================================
Order Items
Shape: (40025, 7)
Columns: ['order_item_id', 'created_at', 'order_id', 'product_id', 'is_primary_item', 'price_usd', 'cogs_usd']
Data Types:
order_item_id        int64
created_at          object
order_id             int64
product_id           int64
is_primary_item      int64
price_usd          float64
cogs_usd           float64
dtype: object
Missing Values:
order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

==================================================
Refunds
Shape: (1731, 5)
Columns: ['order_item_refund_id', 'created_at', 'order_item_id', 'order_id', 'refund_amount_usd']
Data Types:
order_item_refund_id      int64
created_at               object
order_item_id             int64
order_id                  int64
refund_amount_usd       float64
dtype: object
Missing Values:
order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

==================================================
Website Sessions
Shape: (472871, 9)
Columns: ['website_session_id', 'created_at', 'user_id', 'is_repeat_session', 'utm_source', 'utm_campaign', 'utm_content', 'device_type', 'http_referer']
Data Types:
website_session_id     int64
created_at            object
user_id                int64
is_repeat_session      int64
utm_source            object
utm_campaign          object
utm_content           object
device_type           object
http_referer          object
dtype: object
Missing Values:
website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64

==================================================
Website Pageviews
Shape: (1188124, 4)
Columns: ['website_pageview_id', 'created_at', 'website_session_id', 'pageview_url']
Data Types:
website_pageview_id     int64
created_at             object
website_session_id      int64
pageview_url           object
dtype: object
Missing Values:
website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64

### Data Preview

##### Objective

Inspect the first and last few records of every dataset to understand the stored information, verify data consistency, and identify any unusual values.

In [5]:
for name, df in tables.items():
    print("=" * 50)
    print(name)
    # head
    display(df.head())
    # tail
    display(df.tail())
    print()

==================================================
Products

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

==================================================
Orders

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
32308,32309,2015-03-19 03:58:12,472795,394255,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:43,472798,394257,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:28,472809,394268,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:57,472814,394273,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:31,472818,386000,1,1,49.99,19.49

==================================================
Order Items

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
40020,40021,2015-03-19 04:10:43,32310,4,1,29.99,9.49
40021,40022,2015-03-19 05:27:28,32311,2,1,59.99,22.49
40022,40023,2015-03-19 05:27:28,32311,4,0,29.99,9.49
40023,40024,2015-03-19 05:35:57,32312,4,1,29.99,9.49
40024,40025,2015-03-19 05:38:31,32313,1,1,49.99,19.49

==================================================
Refunds

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
1726,1727,2015-03-30 09:37:23,39950,32255,59.99
1727,1728,2015-03-30 21:33:51,39671,32049,49.99
1728,1729,2015-03-31 19:59:48,39729,32090,49.99
1729,1730,2015-04-01 03:54:48,39717,32079,59.99
1730,1731,2015-04-01 18:11:08,39947,32252,45.99

==================================================
Website Sessions

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,NaN,NaN,NaN,mobile,NaN

==================================================
Website Pageviews

   website_pageview_id           created_at  website_session_id pageview_url
0                    1  2012-03-19 08:04:16                   1        /home
1                    2  2012-03-19 08:16:49                   2        /home
2                    3  2012-03-19 08:26:55                   3        /home
3                    4  2012-03-19 08:37:33                   4        /home
4                    5  2012-03-19 09:00:55                   5        /home

,website_pageview_id,created_at,website_session_id,pageview_url
1188119,1188120,2015-03-19 07:57:32,472866,/shipping
1188120,1188121,2015-03-19 07:58:13,472870,/the-original-mr-fuzzy
1188121,1188122,2015-03-19 07:59:07,472866,/billing-2
1188122,1188123,2015-03-19 07:59:08,472871,/home
1188123,1188124,2015-03-19 07:59:32,472868,/the-original-mr-fuzzy